services:
  are-they-alive:
    image: ghcr.io/kostecki/are-they-alive:latest
    restart: unless-stopped
    hostname: ${HOSTNAME}
    ports:
      - ${APP_PORT}:3000
    environment:
      BASE_URL: ${BASE_URL}
      TMDB_API_TOKEN: ${TMDB_API_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  redis:
    image: redis:alpine
    restart: unless-stopped
    hostname: ${REDIS_HOSTNAME}
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly no
    volumes:
      - are-they-alive-redis:/data

volumes:
  are-they-alive-redis:
