services:
  are-they-alive:
    image: ghcr.io/kostecki/are-they-alive:latest
    restart: unless-stopped
    hostname: are-they-alive-docker-tower
    ports:
      - 3003:3000
    environment:
      BASE_URL: ${BASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      VITE_UMAMI_SRC_URL: ${VITE_UMAMI_SRC_URL}
      VITE_UMAMI_WEBSITE_ID: ${VITE_UMAMI_WEBSITE_ID}
  redis:
    image: redis:alpine
    restart: unless-stopped
    hostname: redis-are-they-alive-docker-tower
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly no
    volumes:
      - ata-redis_data:/data

volumes:
  ata-redis_data:
